---
name: Checks

on:
  push:

jobs:
 test-lint:
  name: Test and Lint
  runs-on: ubuntu-20.04
  steps: #Logins into docker hub
   - name: Login to Docker Hub
     uses: docker/login-action@v1
     with:
       username: ${{ secrets.DOCKERHUB_USER }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}
    #Checks our code 
   - name: Checkout
     uses: actions/checkout@v2
     # Runs the test using docker compose
   - name: Test
     run: docker compose run --rm app sh -c "python manage.py test"
     # Runs the lint using docker compose
   - name: Lint 
     run : docker compose run --rm app sh -c "flake8"
